Fix #14 - Make Docker more flexible
authzforce/fiware pull request #15
Opened 2018-11-17 07:37 UTC by jason-fox

* Expose Volume so Policies can be injected
* Remove hard-coded 8080 port and replace with optional `ENV` parameter in case port 8080 is in use. Port 8080 remains the default.

2018-11-19 01:03 UTC, cdanger requested changes
**Could you remove the changes to lines 74-75 (EXPOSE 8080)?** 
This change is useless because this port 8080 is only a port inside the container and not on the host, you can map it to any port you want on the host by using docker `-p` flag. For example:

`-p 80:8080`:  Map TCP port 8080 in the container to port 80 on the Docker host.

So no need for an environment variable. More info on docker user guide: https://docs.docker.com/config/containers/container-networking/

2018-11-19 14:32 UTC, jason-fox commented
The main idea behind exposing a port with an `ENV` variable is that is would then be possible to connect via HTTP container 8080 or HTTPS container 8443.

An alternative would be:

```
EXPOSE 8080 8443
```

 I but l had assumed that you'd only want the one port exposed if you're using HTTPS rather than still opening 8080, or would exposing two fixed ports make more sense to you?

2018-11-19 15:45 UTC, jason-fox commented on docker/Dockerfile
> +EXPOSE 8080
Port reverted. Fixed - 683780b

2018-11-25 02:22 UTC, cdanger commented on docker/Dockerfile
> +EXPOSE 8080
Unfortunately, the authzforce docker image does not support HTTPS, so there is no HTTPS port to expose. An alternative is to use a HTTPS reverse proxy (Apache, NGINX...). If you still want native support for HTTPS in the docker image, you could make a feature request (and associated pull request if willing to implement) for this. Not sure this can be easily done with the official docker image of tomcat that we are using as base image. See [this issue](https://github.com/docker-library/tomcat/issues/50). Maybe use another base image for tomcat, as suggested in the issue I just mentioned. Or [this one](https://github.com/Unidata/tomcat-docker). Neither tested one or the other. To my knowledge, the reverse-proxy solution is very popular.

2018-11-25 02:23 UTC, cdanger approved these changes

2018-11-25 02:24 UTC, merged